### ISSUE TITLE
关于文章 Update Frequency 的实现

### ISSUE THREAD

**Issue by jzndd** [opendilab/SO2#3]
尊敬的作者：
您好！在 SO2 中，原文提到了 _Specifically, we denote the update frequency after each online sample collection as Nupc, where upc means update per collection._  其中 Nupc 设置为 10， 但是在代码中似乎默认值为 1 ，请问有没有关于这个细节的进一步解释？

**Comment by jzndd** [comment]
以及文中提到了会更新 Nupc 次 value network ， 这是一个常见的做法，但是代码中的实现是同时更新多次 value network 和 actor network （在设置 Nupc 大于 1的情况下）；似乎这样的代码实现与文章的描述并没有对齐。

**Comment by YinminZhang** [comment]
> 尊敬的作者： 您好！在 SO2 中，原文提到了 _Specifically, we denote the update frequency after each online sample collection as Nupc, where upc means update per collection._ 其中 Nupc 设置为 10， 但是在代码中似乎默认值为 1 ，请问有没有关于这个细节的进一步解释？

感谢您的关注, 我们发现目前这版code由于merge的原因与论文细节有不一致的部分,同时无法复现论文中的性能

我们提供了原始的代码在 [#issue1](https://github.com/opendilab/SO2/issues/2#issuecomment-2172364364)

**Comment by YinminZhang** [comment]
> 以及文中提到了会更新 Nupc 次 value network ， 这是一个常见的做法，但是代码中的实现是同时更新多次 value network 和 actor network （在设置 Nupc 大于 1的情况下）；似乎这样的代码实现与文章的描述并没有对齐。

我们在Appendix部分提供了对比,only value network update和同时更新两者差异不大

**Comment by YinminZhang** [comment]
Considering the difficulty of tracking the main branch in the DI-engine updates, we have updated the independent code branch to reproduce the results in the paper.

You can check the details in the code branch.
