### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by asyua-ye** [opendilab/SO2#4]
if args.ckpt_path is not None:
        main_config.policy.learn.learner.load_path=args.ckpt_path
    else:
        main_config.policy.learn.learner.load_path=f'ckpt/{args.env_id}.ckpt'

请问作者，我看新的代码里面，这段代码要直接提供经过offline预训练阶段的模型，如果要用train.py从offline预训练一直走到在线的微调，该怎么设置您代码的超参数？

**Comment by YinminZhang** [comment]
建议download我们提供的ckpt进行后续微调
[Google Drive](https://drive.google.com/file/d/1ShHXQw2ox3F-9WKLOZo8Qnjn0mEtaQdl/view?usp=drive_link)
